# Generated by Django 4.2.16 on 2024-11-06 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stopwatch.models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('access_datetime', models.DateTimeField(default=stopwatch.models.in_30_days)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
