# Generated by Django 4.2.16 on 2024-11-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0002_accesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
